TARGET = myprog
DEPS = ../libperson/libperson.so ../mystat_lib/libmystat.a
CC = gcc
INC = -I./
CONFIG = DEFAULT
CFLAGS += -g3 -Wall -Wextra -std=c11 -DCONFIG=$(CONFIG) 
LDFLAGS += 


include ../build.mk